modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/RandomCommand/issues"
license = "MIT"

[[mods]]
modId = "random_command"
version = "${version}"
displayName = "Random Command"
authors = "IAFEnvoy"
description = '''
A collection of useful, permission controllable commands.
'''
logoFile = "logo.png"

[[dependencies.random_command]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.random_command]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"